### PR TITLE
Pull changes back to original repo

### PR DESCRIPTION
**Pull request by tsvi**

### CODE REVIEW

**Comment by tsvi** [comment]
Thanks, @blutsvente for all the additions, incorporating them back into my own repo.

**Comment by blutsvente** [comment]
Welcome, tsvi. Without your excellent groundwork I wouldn't have known where to start.

**Comment by tsvi** [comment]
@blutsvente, do you mind if we setup the package channel repo to officially point to my version since you're using a fork of my repo. It might make things easier in the future, if others try to collaborate on my repo.

**Comment by blutsvente** [comment]
That makes sense! But could we wait until my pull-request of the package channel has been merged? They seem to have a backlog of a couple of months, and I don't want to jump to the end of the queue again (also, I am actively using it and might add some more bugfixes short term). After that it's easy to change by forking package_control_channel again/modifying the s.json file/do pull-request

**Comment by tsvi** [comment]
Great. Let's continue collaborating on this.

Feel free to create pull requests, I usually merge them in quickly.

**Pull request merged**
