### PR TITLE
Minor fixes; added .tmPreferences

### PR DESCRIPTION
**Pull request by blutsvente**
See Changelog.md

### CODE REVIEW

**Comment by tsvi** [comment]
This looks amazing. But I prefer if we use // as a comment. Any thoughts?
Haven't delved in sublime for some time, maybe we could make this as a user setting.

**Comment by blutsvente** [comment]
Hi,
I don’t have any preference for the comment. You can change it to //.
As for the user settings, I presume you would need some Python code that uses the ST3 api...I haven’t done anything this direction yet. Might be a nice project. 
Cheers.

Von meinem iPod gesendet

**Comment by blutsvente** [comment]
I made the comment-symbol change and made this a release, 1.0.2

**Review by tsvi — APPROVED** [review]

**Comment by blutsvente** [comment]
I think you need to resolve the conflict before the pull-request is merged into the master branch. I don't have write permissions.

**Comment by tsvi** [comment]
Fixes #1

**Pull request merged**
